package tif.TagEntries;

import tif.DirectoryIdentifier;
import tif.TagHint;

public enum TagEXIF implements Taggable
{
    EXIF_TAG_GLOBAL_PARAMETERS_IFD(0x0190, DirectoryIdentifier.EXIF_DIRECTORY_SUBIFD),
    EXIF_TAG_EXPOSURE_TIME(0x829A, DirectoryIdentifier.EXIF_DIRECTORY_SUBIFD),
    EXIF_TAG_FNUMBER(0x829D, DirectoryIdentifier.EXIF_DIRECTORY_SUBIFD),
    EXIF_TAG_EXPOSURE_PROGRAM(0x8822, DirectoryIdentifier.EXIF_DIRECTORY_SUBIFD),
    EXIF_TAG_SPECTRAL_SENSITIVITY(0x8824, DirectoryIdentifier.EXIF_DIRECTORY_SUBIFD),
    EXIF_TAG_ISO(0x8827, DirectoryIdentifier.EXIF_DIRECTORY_SUBIFD),
    EXIF_TAG_TIME_ZONE_OFFSET(0x882A, DirectoryIdentifier.EXIF_DIRECTORY_SUBIFD),
    EXIF_TAG_SELF_TIMER_MODE(0x882B, DirectoryIdentifier.EXIF_DIRECTORY_SUBIFD),
    EXIF_TAG_SENSITIVITY_TYPE(0x8830, DirectoryIdentifier.EXIF_DIRECTORY_SUBIFD),
    EXIF_TAG_STANDARD_OUTPUT_SENSITIVITY(0x8831, DirectoryIdentifier.EXIF_DIRECTORY_SUBIFD),
    EXIF_TAG_RECOMMENDED_EXPOSURE_INDEX(0x8832, DirectoryIdentifier.EXIF_DIRECTORY_SUBIFD),
    EXIF_TAG_ISOSPEED(0x8833, DirectoryIdentifier.EXIF_DIRECTORY_SUBIFD),
    EXIF_TAG_ISOSPEED_LATITUDEYYY(0x8834, DirectoryIdentifier.EXIF_DIRECTORY_SUBIFD),
    EXIF_TAG_ISOSPEED_LATITUDEZZZ(0x8835, DirectoryIdentifier.EXIF_DIRECTORY_SUBIFD),
    EXIF_TAG_EXIF_VERSION(0x9000, DirectoryIdentifier.EXIF_DIRECTORY_SUBIFD, TagHint.HINT_STRING),
    EXIF_TAG_DATE_TIME_ORIGINAL(0x9003, DirectoryIdentifier.EXIF_DIRECTORY_SUBIFD, TagHint.HINT_DATE),
    EXIF_TAG_CREATE_DATE(0x9004, DirectoryIdentifier.EXIF_DIRECTORY_SUBIFD, TagHint.HINT_DATE),
    EXIF_TAG_GOOGLE_PLUS_UPLOAD_CODE(0x9009, DirectoryIdentifier.EXIF_DIRECTORY_SUBIFD),
    EXIF_TAG_OFFSET_TIME(0x9010, DirectoryIdentifier.EXIF_DIRECTORY_SUBIFD),
    EXIF_TAG_OFFSET_TIME_ORIGINAL(0x9011, DirectoryIdentifier.EXIF_DIRECTORY_SUBIFD),
    EXIF_TAG_OFFSET_TIME_DIGITIZED(0x9012, DirectoryIdentifier.EXIF_DIRECTORY_SUBIFD),
    EXIF_TAG_COMPONENTS_CONFIGURATION(0x9101, DirectoryIdentifier.EXIF_DIRECTORY_SUBIFD, TagHint.HINT_BYTE),
    EXIF_TAG_COMPRESSED_BITS_PER_PIXEL(0x9102, DirectoryIdentifier.EXIF_DIRECTORY_SUBIFD),
    EXIF_TAG_SHUTTER_SPEED_VALUE(0x9201, DirectoryIdentifier.EXIF_DIRECTORY_SUBIFD),
    EXIF_TAG_APERTURE_VALUE(0x9202, DirectoryIdentifier.EXIF_DIRECTORY_SUBIFD),
    EXIF_TAG_BRIGHTNESS_VALUE(0x9203, DirectoryIdentifier.EXIF_DIRECTORY_SUBIFD),
    EXIF_TAG_EXPOSURE_COMPENSATION(0x9204, DirectoryIdentifier.EXIF_DIRECTORY_SUBIFD),
    EXIF_TAG_MAX_APERTURE_VALUE(0x9205, DirectoryIdentifier.EXIF_DIRECTORY_SUBIFD),
    EXIF_TAG_SUBJECT_DISTANCE(0x9206, DirectoryIdentifier.EXIF_DIRECTORY_SUBIFD),
    EXIF_TAG_METERING_MODE(0x9207, DirectoryIdentifier.EXIF_DIRECTORY_SUBIFD),
    EXIF_TAG_LIGHT_SOURCE(0x9208, DirectoryIdentifier.EXIF_DIRECTORY_SUBIFD),
    EXIF_TAG_FLASH(0x9209, DirectoryIdentifier.EXIF_DIRECTORY_SUBIFD),
    EXIF_TAG_FOCAL_LENGTH(0x920A, DirectoryIdentifier.EXIF_DIRECTORY_SUBIFD),
    EXIF_TAG_IMAGE_NUMBER(0x9211, DirectoryIdentifier.EXIF_DIRECTORY_SUBIFD),
    EXIF_TAG_SECURITY_CLASSIFICATION(0x9212, DirectoryIdentifier.EXIF_DIRECTORY_SUBIFD),
    EXIF_TAG_IMAGE_HISTORY(0x9213, DirectoryIdentifier.EXIF_DIRECTORY_SUBIFD),
    EXIF_TAG_SUBJECT_AREA(0x9214, DirectoryIdentifier.EXIF_DIRECTORY_SUBIFD),
    EXIF_TAG_MAKER_NOTE(0x927C, DirectoryIdentifier.EXIF_DIRECTORY_SUBIFD, TagHint.HINT_MASK),
    EXIF_TAG_USER_COMMENT(0x9286, DirectoryIdentifier.EXIF_DIRECTORY_SUBIFD, TagHint.HINT_STRING),
    EXIF_TAG_SUB_SEC_TIME(0x9290, DirectoryIdentifier.EXIF_DIRECTORY_SUBIFD),
    EXIF_TAG_SUB_SEC_TIME_ORIGINAL(0x9291, DirectoryIdentifier.EXIF_DIRECTORY_SUBIFD),
    EXIF_TAG_SUB_SEC_TIME_DIGITIZED(0x9292, DirectoryIdentifier.EXIF_DIRECTORY_SUBIFD),
    EXIF_TAG_AMBIENT_TEMPERATURE(0x9400, DirectoryIdentifier.EXIF_DIRECTORY_SUBIFD),
    EXIF_TAG_HUMIDITY(0x9401, DirectoryIdentifier.EXIF_DIRECTORY_SUBIFD),
    EXIF_TAG_PRESSURE(0x9402, DirectoryIdentifier.EXIF_DIRECTORY_SUBIFD),
    EXIF_TAG_WATER_DEPTH(0x9403, DirectoryIdentifier.EXIF_DIRECTORY_SUBIFD),
    EXIF_TAG_ACCELERATION(0x9404, DirectoryIdentifier.EXIF_DIRECTORY_SUBIFD),
    EXIF_TAG_CAMERA_ELEVATION_ANGLE(0x9405, DirectoryIdentifier.EXIF_DIRECTORY_SUBIFD),
    EXIF_TAG_XIAOMI_SETTINGS(0x9999, DirectoryIdentifier.EXIF_DIRECTORY_SUBIFD),
    EXIF_TAG_XIAOMI_MODEL(0x9A00, DirectoryIdentifier.EXIF_DIRECTORY_SUBIFD),
    EXIF_TAG_FLASHPIX_VERSION(0xA000, DirectoryIdentifier.EXIF_DIRECTORY_SUBIFD, TagHint.HINT_STRING),
    EXIF_TAG_COLOR_SPACE(0xA001, DirectoryIdentifier.EXIF_DIRECTORY_SUBIFD),
    EXIF_TAG_EXIF_IMAGE_WIDTH(0xA002, DirectoryIdentifier.EXIF_DIRECTORY_SUBIFD),
    EXIF_TAG_EXIF_IMAGE_HEIGHT(0xA003, DirectoryIdentifier.EXIF_DIRECTORY_SUBIFD),
    EXIF_TAG_RELATED_SOUND_FILE(0xA004, DirectoryIdentifier.EXIF_DIRECTORY_SUBIFD),
    EXIF_TAG_INTEROP_POINTER(0xA005, DirectoryIdentifier.EXIF_DIRECTORY_SUBIFD),
    EXIF_TAG_FLASH_ENERGY(0xA20B, DirectoryIdentifier.EXIF_DIRECTORY_SUBIFD),
    EXIF_TAG_FOCAL_PLANE_XRESOLUTION(0xA20E, DirectoryIdentifier.EXIF_DIRECTORY_SUBIFD),
    EXIF_TAG_FOCAL_PLANE_YRESOLUTION(0xA20F, DirectoryIdentifier.EXIF_DIRECTORY_SUBIFD),
    EXIF_TAG_FOCAL_PLANE_RESOLUTION_UNIT(0xA210, DirectoryIdentifier.EXIF_DIRECTORY_SUBIFD),
    EXIF_TAG_SUBJECT_LOCATION(0xA214, DirectoryIdentifier.EXIF_DIRECTORY_SUBIFD),
    EXIF_TAG_EXPOSURE_INDEX(0xA215, DirectoryIdentifier.EXIF_DIRECTORY_SUBIFD),
    EXIF_TAG_SENSING_METHOD(0xA217, DirectoryIdentifier.EXIF_DIRECTORY_SUBIFD),
    EXIF_TAG_FILE_SOURCE(0xA300, DirectoryIdentifier.EXIF_DIRECTORY_SUBIFD),
    EXIF_TAG_SCENE_TYPE(0xA301, DirectoryIdentifier.EXIF_DIRECTORY_SUBIFD, TagHint.HINT_BYTE),
    EXIF_TAG_CFAPATTERN(0xA302, DirectoryIdentifier.EXIF_DIRECTORY_SUBIFD),
    EXIF_TAG_CUSTOM_RENDERED(0xA401, DirectoryIdentifier.EXIF_DIRECTORY_SUBIFD),
    EXIF_TAG_EXPOSURE_MODE(0xA402, DirectoryIdentifier.EXIF_DIRECTORY_SUBIFD),
    EXIF_TAG_WHITE_BALANCE(0xA403, DirectoryIdentifier.EXIF_DIRECTORY_SUBIFD),
    EXIF_TAG_DIGITAL_ZOOM_RATIO(0xA404, DirectoryIdentifier.EXIF_DIRECTORY_SUBIFD),
    EXIF_TAG_FOCAL_LENGTH_IN_35MM_FORMAT(0xA405, DirectoryIdentifier.EXIF_DIRECTORY_SUBIFD),
    EXIF_TAG_SCENE_CAPTURE_TYPE(0xA406, DirectoryIdentifier.EXIF_DIRECTORY_SUBIFD),
    EXIF_TAG_GAIN_CONTROL(0xA407, DirectoryIdentifier.EXIF_DIRECTORY_SUBIFD),
    EXIF_TAG_CONTRAST(0xA408, DirectoryIdentifier.EXIF_DIRECTORY_SUBIFD),
    EXIF_TAG_SATURATION(0xA409, DirectoryIdentifier.EXIF_DIRECTORY_SUBIFD),
    EXIF_TAG_SHARPNESS(0xA40A, DirectoryIdentifier.EXIF_DIRECTORY_SUBIFD),
    EXIF_TAG_SUBJECT_DISTANCE_RANGE(0xA40C, DirectoryIdentifier.EXIF_DIRECTORY_SUBIFD),
    EXIF_TAG_IMAGE_UNIQUE_ID(0xA420, DirectoryIdentifier.EXIF_DIRECTORY_SUBIFD),
    EXIF_TAG_CAMERA_OWNER_NAME(0xA430, DirectoryIdentifier.EXIF_DIRECTORY_SUBIFD),
    EXIF_TAG_BODY_SERIAL_NUMBER(0xA431, DirectoryIdentifier.EXIF_DIRECTORY_SUBIFD),
    EXIF_TAG_LENS_INFO(0xA432, DirectoryIdentifier.EXIF_DIRECTORY_SUBIFD),
    EXIF_TAG_LENS_MAKE(0xA433, DirectoryIdentifier.EXIF_DIRECTORY_SUBIFD),
    EXIF_TAG_LENS_MODEL(0xA434, DirectoryIdentifier.EXIF_DIRECTORY_SUBIFD),
    EXIF_TAG_LENS_SERIAL_NUMBER(0xA435, DirectoryIdentifier.EXIF_DIRECTORY_SUBIFD),
    EXIF_TAG_IMAGE_TITLE(0xA436, DirectoryIdentifier.EXIF_DIRECTORY_SUBIFD),
    EXIF_TAG_PHOTOGRAPHER(0xA437, DirectoryIdentifier.EXIF_DIRECTORY_SUBIFD),
    EXIF_TAG_IMAGE_EDITOR(0xA438, DirectoryIdentifier.EXIF_DIRECTORY_SUBIFD),
    EXIF_TAG_CAMERA_FIRMWARE(0xA439, DirectoryIdentifier.EXIF_DIRECTORY_SUBIFD),
    EXIF_TAG_RAWDEVELOPING_SOFTWARE(0xA43A, DirectoryIdentifier.EXIF_DIRECTORY_SUBIFD),
    EXIF_TAG_IMAGE_EDITING_SOFTWARE(0xA43B, DirectoryIdentifier.EXIF_DIRECTORY_SUBIFD),
    EXIF_TAG_METADATA_EDITING_SOFTWARE(0xA43C, DirectoryIdentifier.EXIF_DIRECTORY_SUBIFD),
    EXIF_TAG_COMPOSITE_IMAGE(0xA460, DirectoryIdentifier.EXIF_DIRECTORY_SUBIFD),
    EXIF_TAG_COMPOSITE_IMAGE_COUNT(0xA461, DirectoryIdentifier.EXIF_DIRECTORY_SUBIFD),
    EXIF_TAG_COMPOSITE_IMAGE_EXPOSURE_TIMES(0xA462, DirectoryIdentifier.EXIF_DIRECTORY_SUBIFD),
    EXIF_TAG_GAMMA(0xA500, DirectoryIdentifier.EXIF_DIRECTORY_SUBIFD),
    EXIF_TAG_HASSELBLAD_EXIF(0xC51B, DirectoryIdentifier.EXIF_DIRECTORY_SUBIFD),
    EXIF_TAG_PADDING(0xEA1C, DirectoryIdentifier.EXIF_DIRECTORY_SUBIFD),
    EXIF_TAG_OFFSET_SCHEMA(0xEA1D, DirectoryIdentifier.EXIF_DIRECTORY_SUBIFD),
    EXIF_TAG_OWNER_NAME(0xFDE8, DirectoryIdentifier.EXIF_DIRECTORY_SUBIFD),
    EXIF_TAG_SERIAL_NUMBER(0xFDE9, DirectoryIdentifier.EXIF_DIRECTORY_SUBIFD),
    EXIF_TAG_LENS(0xFDEA, DirectoryIdentifier.EXIF_DIRECTORY_SUBIFD),
    EXIF_TAG_RAW_FILE(0xFE4C, DirectoryIdentifier.EXIF_DIRECTORY_SUBIFD),
    EXIF_TAG_CONVERTER(0xFE4D, DirectoryIdentifier.EXIF_DIRECTORY_SUBIFD),
    EXIF_TAG_WHITE_BALANCE_STRING(0xFE4E, DirectoryIdentifier.EXIF_DIRECTORY_SUBIFD),
    EXIF_TAG_EXPOSURE(0xFE51, DirectoryIdentifier.EXIF_DIRECTORY_SUBIFD),
    EXIF_TAG_SHADOWS(0xFE52, DirectoryIdentifier.EXIF_DIRECTORY_SUBIFD),
    EXIF_TAG_BRIGHTNESS(0xFE53, DirectoryIdentifier.EXIF_DIRECTORY_SUBIFD),
    EXIF_TAG_CONTRAST_STRING(0xFE54, DirectoryIdentifier.EXIF_DIRECTORY_SUBIFD),
    EXIF_TAG_SATURATION_STRING(0xFE55, DirectoryIdentifier.EXIF_DIRECTORY_SUBIFD),
    EXIF_TAG_SHARPNESS_STRING(0xFE56, DirectoryIdentifier.EXIF_DIRECTORY_SUBIFD),
    EXIF_TAG_SMOOTHNESS(0xFE57, DirectoryIdentifier.EXIF_DIRECTORY_SUBIFD),
    EXIF_TAG_MOIRE_FILTER(0xFE58, DirectoryIdentifier.EXIF_DIRECTORY_SUBIFD);

    private final int numID;
    private final DirectoryIdentifier directory;
    private final TagHint hint;

    private TagEXIF(int id, DirectoryIdentifier dir)
    {
        this(id, dir, TagHint.HINT_DEFAULT);
    }

    private TagEXIF(int id, DirectoryIdentifier dir, TagHint clue)
    {
        numID = id;
        directory = dir;
        hint = clue;
    }

    @Override
    public int getNumberID()
    {
        return numID;
    }

    @Override
    public DirectoryIdentifier getDirectoryType()
    {
        return directory;
    }

    @Override
    public TagHint getHint()
    {
        return hint;
    }
}