package tif.TagEntries;

import tif.DirectoryIdentifier;
import tif.TagHint;

public enum TagSUBIFD implements Taggable
{
    SUBIFD_TAG_SAMPLE_FORMAT(0x0153, DirectoryIdentifier.TIFF_DIRECTORY_SUBIFD),
    SUBIFD_TAG_VIGNETTING_CORRECTION(0x7031, DirectoryIdentifier.TIFF_DIRECTORY_SUBIFD),
    SUBIFD_TAG_VIGNETTING_CORR_PARAMS(0x7032, DirectoryIdentifier.TIFF_DIRECTORY_SUBIFD),
    SUBIFD_TAG_CHROMATIC_ABERRATION_CORRECTION(0x7034, DirectoryIdentifier.TIFF_DIRECTORY_SUBIFD),
    SUBIFD_TAG_CHROMATIC_ABERRATION_CORR_PARAMS(0x7035, DirectoryIdentifier.TIFF_DIRECTORY_SUBIFD),
    SUBIFD_TAG_DISTORTION_CORRECTION(0x7036, DirectoryIdentifier.TIFF_DIRECTORY_SUBIFD),
    SUBIFD_TAG_DISTORTION_CORR_PARAMS(0x7037, DirectoryIdentifier.TIFF_DIRECTORY_SUBIFD),
    SUBIFD_TAG_SONY_RAW_IMAGE_SIZE(0x7038, DirectoryIdentifier.TIFF_DIRECTORY_SUBIFD),
    SUBIFD_TAG_BLACK_LEVEL_SONY(0x7310, DirectoryIdentifier.TIFF_DIRECTORY_SUBIFD),
    SUBIFD_TAG_WB_RGGBLEVELS(0x7313, DirectoryIdentifier.TIFF_DIRECTORY_SUBIFD),
    SUBIFD_TAG_SONY_CROP_TOP_LEFT(0x74C7, DirectoryIdentifier.TIFF_DIRECTORY_SUBIFD),
    SUBIFD_TAG_SONY_CROP_SIZE(0x74C8, DirectoryIdentifier.TIFF_DIRECTORY_SUBIFD),
    SUBIFD_TAG_CFAREPEAT_PATTERN_DIM(0x828D, DirectoryIdentifier.TIFF_DIRECTORY_SUBIFD),
    SUBIFD_TAG_CFAPATTERN2(0x828E, DirectoryIdentifier.TIFF_DIRECTORY_SUBIFD),
    SUBIFD_TAG_CFAPLANE_COLOR(0xC616, DirectoryIdentifier.TIFF_DIRECTORY_SUBIFD),
    SUBIFD_TAG_CFALAYOUT(0xC617, DirectoryIdentifier.TIFF_DIRECTORY_SUBIFD),
    SUBIFD_TAG_LINEARIZATION_TABLE(0xC618, DirectoryIdentifier.TIFF_DIRECTORY_SUBIFD),
    SUBIFD_TAG_BLACK_LEVEL_REPEAT_DIM(0xC619, DirectoryIdentifier.TIFF_DIRECTORY_SUBIFD),
    SUBIFD_TAG_BLACK_LEVEL(0xC61A, DirectoryIdentifier.TIFF_DIRECTORY_SUBIFD),
    SUBIFD_TAG_BLACK_LEVEL_DELTA_H(0xC61B, DirectoryIdentifier.TIFF_DIRECTORY_SUBIFD),
    SUBIFD_TAG_BLACK_LEVEL_DELTA_V(0xC61C, DirectoryIdentifier.TIFF_DIRECTORY_SUBIFD),
    SUBIFD_TAG_WHITE_LEVEL(0xC61D, DirectoryIdentifier.TIFF_DIRECTORY_SUBIFD),
    SUBIFD_TAG_DEFAULT_SCALE(0xC61E, DirectoryIdentifier.TIFF_DIRECTORY_SUBIFD),
    SUBIFD_TAG_DEFAULT_CROP_ORIGIN(0xC61F, DirectoryIdentifier.TIFF_DIRECTORY_SUBIFD),
    SUBIFD_TAG_DEFAULT_CROP_SIZE(0xC620, DirectoryIdentifier.TIFF_DIRECTORY_SUBIFD),
    SUBIFD_TAG_BAYER_GREEN_SPLIT(0xC62D, DirectoryIdentifier.TIFF_DIRECTORY_SUBIFD),
    SUBIFD_TAG_CHROMA_BLUR_RADIUS(0xC631, DirectoryIdentifier.TIFF_DIRECTORY_SUBIFD),
    SUBIFD_TAG_ANTI_ALIAS_STRENGTH(0xC632, DirectoryIdentifier.TIFF_DIRECTORY_SUBIFD),
    SUBIFD_TAG_BEST_QUALITY_SCALE(0xC65C, DirectoryIdentifier.TIFF_DIRECTORY_SUBIFD),
    SUBIFD_TAG_ACTIVE_AREA(0xC68D, DirectoryIdentifier.TIFF_DIRECTORY_SUBIFD),
    SUBIFD_TAG_MASKED_AREAS(0xC68E, DirectoryIdentifier.TIFF_DIRECTORY_SUBIFD),
    SUBIFD_TAG_NOISE_REDUCTION_APPLIED(0xC6F7, DirectoryIdentifier.TIFF_DIRECTORY_SUBIFD),
    SUBIFD_TAG_OPCODE_LIST1(0xC740, DirectoryIdentifier.TIFF_DIRECTORY_SUBIFD),
    SUBIFD_TAG_OPCODE_LIST2(0xC741, DirectoryIdentifier.TIFF_DIRECTORY_SUBIFD),
    SUBIFD_TAG_OPCODE_LIST3(0xC74E, DirectoryIdentifier.TIFF_DIRECTORY_SUBIFD),
    SUBIFD_TAG_NOISE_PROFILE(0xC761, DirectoryIdentifier.TIFF_DIRECTORY_SUBIFD),
    SUBIFD_TAG_DEFAULT_USER_CROP(0xC7B5, DirectoryIdentifier.TIFF_DIRECTORY_SUBIFD),
    SUBIFD_TAG_PROFILE_GAIN_TABLE_MAP(0xCD2D, DirectoryIdentifier.TIFF_DIRECTORY_SUBIFD),
    SUBIFD_TAG_SEMANTIC_NAME(0xCD2E, DirectoryIdentifier.TIFF_DIRECTORY_SUBIFD),
    SUBIFD_TAG_SEMANTIC_INSTANCE_ID(0xCD30, DirectoryIdentifier.TIFF_DIRECTORY_SUBIFD),
    SUBIFD_TAG_MASK_SUB_AREA(0xCD38, DirectoryIdentifier.TIFF_DIRECTORY_SUBIFD),
    SUBIFD_TAG_COLUMN_INTERLEAVE_FACTOR(0xCD43, DirectoryIdentifier.TIFF_DIRECTORY_SUBIFD),
    SUBIFD_TAG_CACHE_VERSION(0xC7AA, DirectoryIdentifier.TIFF_DIRECTORY_SUBIFD2);

    private final int numID;
    private final DirectoryIdentifier directory;
    private final TagHint hint;

    private TagSUBIFD(int id, DirectoryIdentifier dir)
    {
        this(id, dir, TagHint.HINT_DEFAULT);
    }

    private TagSUBIFD(int id, DirectoryIdentifier dir, TagHint clue)
    {
        numID = id;
        directory = dir;
        hint = clue;
    }

    public int getNumberID()
    {
        return numID;
    }

    public DirectoryIdentifier getDirectoryType()
    {
        return directory;
    }

    public TagHint getHint()
    {
        return hint;
    }
}