package tif.tagspecs;

import tif.DirectoryIdentifier;
import tif.TagHint;

public enum TagIFD_Baseline implements Taggable
{
    IFD_NEW_SUBFILE_TYPE(0x00FE, DirectoryIdentifier.IFD_BASELINE_DIRECTORY),
    IFD_SUBFILE_TYPE(0x00FF, DirectoryIdentifier.IFD_BASELINE_DIRECTORY),
    IFD_IMAGE_WIDTH(0x0100, DirectoryIdentifier.IFD_BASELINE_DIRECTORY),
    IFD_IMAGE_LENGTH(0x0101, DirectoryIdentifier.IFD_BASELINE_DIRECTORY),
    IFD_BITS_PER_SAMPLE(0x0102, DirectoryIdentifier.IFD_BASELINE_DIRECTORY),
    IFD_COMPRESSION(0x0103, DirectoryIdentifier.IFD_BASELINE_DIRECTORY),
    IFD_PHOTOMETRIC_INTERPRETATION(0x0106, DirectoryIdentifier.IFD_BASELINE_DIRECTORY),
    IFD_THRESHHOLDING(0x0107, DirectoryIdentifier.IFD_BASELINE_DIRECTORY),
    IFD_CELL_WIDTH(0x0108, DirectoryIdentifier.IFD_BASELINE_DIRECTORY),
    IFD_CELL_LENGTH(0x0109, DirectoryIdentifier.IFD_BASELINE_DIRECTORY),
    IFD_FILL_ORDER(0x010A, DirectoryIdentifier.IFD_BASELINE_DIRECTORY),
    IFD_DOCUMENT_NAME(0x010D, DirectoryIdentifier.IFD_BASELINE_DIRECTORY),
    IFD_IMAGE_DESCRIPTION(0x010E, DirectoryIdentifier.IFD_BASELINE_DIRECTORY),
    IFD_MAKE(0x010F, DirectoryIdentifier.IFD_BASELINE_DIRECTORY),
    IFD_MODEL(0x0110, DirectoryIdentifier.IFD_BASELINE_DIRECTORY),
    IFD_STRIP_OFFSETS(0x0111, DirectoryIdentifier.IFD_BASELINE_DIRECTORY),
    IFD_ORIENTATION(0x0112, DirectoryIdentifier.IFD_BASELINE_DIRECTORY),
    IFD_SAMPLES_PER_PIXEL(0x0115, DirectoryIdentifier.IFD_BASELINE_DIRECTORY),
    IFD_ROWS_PER_STRIP(0x0116, DirectoryIdentifier.IFD_BASELINE_DIRECTORY),
    IFD_STRIP_BYTE_COUNTS(0x0117, DirectoryIdentifier.IFD_BASELINE_DIRECTORY),
    IFD_MIN_SAMPLE_VALUE(0x0118, DirectoryIdentifier.IFD_BASELINE_DIRECTORY),
    IFD_MAX_SAMPLE_VALUE(0x0119, DirectoryIdentifier.IFD_BASELINE_DIRECTORY),
    IFD_XRESOLUTION(0x011A, DirectoryIdentifier.IFD_BASELINE_DIRECTORY),
    IFD_YRESOLUTION(0x011B, DirectoryIdentifier.IFD_BASELINE_DIRECTORY),
    IFD_PLANAR_CONFIGURATION(0x011C, DirectoryIdentifier.IFD_BASELINE_DIRECTORY),
    IFD_PAGE_NAME(0x011D, DirectoryIdentifier.IFD_BASELINE_DIRECTORY),
    IFD_XPOSITION(0x011E, DirectoryIdentifier.IFD_BASELINE_DIRECTORY),
    IFD_YPOSITION(0x011F, DirectoryIdentifier.IFD_BASELINE_DIRECTORY),
    IFD_FREE_OFFSETS(0x0120, DirectoryIdentifier.IFD_BASELINE_DIRECTORY),
    IFD_FREE_BYTE_COUNTS(0x0121, DirectoryIdentifier.IFD_BASELINE_DIRECTORY),
    IFD_GRAY_RESPONSE_UNIT(0x0122, DirectoryIdentifier.IFD_BASELINE_DIRECTORY),
    IFD_GRAY_RESPONSE_CURVE(0x0123, DirectoryIdentifier.IFD_BASELINE_DIRECTORY),
    IFD_T4OPTIONS(0x0124, DirectoryIdentifier.IFD_BASELINE_DIRECTORY),
    IFD_T6OPTIONS(0x0125, DirectoryIdentifier.IFD_BASELINE_DIRECTORY),
    IFD_RESOLUTION_UNIT(0x0128, DirectoryIdentifier.IFD_BASELINE_DIRECTORY),
    IFD_PAGE_NUMBER(0x0129, DirectoryIdentifier.IFD_BASELINE_DIRECTORY),
    IFD_TRANSFER_FUNCTION(0x012D, DirectoryIdentifier.IFD_BASELINE_DIRECTORY),
    IFD_SOFTWARE(0x0131, DirectoryIdentifier.IFD_BASELINE_DIRECTORY),
    IFD_DATE_TIME(0x0132, DirectoryIdentifier.IFD_BASELINE_DIRECTORY, TagHint.HINT_DATE),
    IFD_ARTIST(0x013B, DirectoryIdentifier.IFD_BASELINE_DIRECTORY),
    IFD_HOST_COMPUTER(0x013C, DirectoryIdentifier.IFD_BASELINE_DIRECTORY),
    IFD_PREDICTOR(0x013D, DirectoryIdentifier.IFD_BASELINE_DIRECTORY),
    IFD_WHITE_POINT(0x013E, DirectoryIdentifier.IFD_BASELINE_DIRECTORY),
    IFD_PRIMARY_CHROMATICITIES(0x013F, DirectoryIdentifier.IFD_BASELINE_DIRECTORY),
    IFD_COLOR_MAP(0x0140, DirectoryIdentifier.IFD_BASELINE_DIRECTORY),
    IFD_HALFTONE_HINTS(0x0141, DirectoryIdentifier.IFD_BASELINE_DIRECTORY),
    IFD_TILE_WIDTH(0x0142, DirectoryIdentifier.IFD_BASELINE_DIRECTORY),
    IFD_TILE_LENGTH(0x0143, DirectoryIdentifier.IFD_BASELINE_DIRECTORY),
    IFD_TILE_OFFSETS(0x0144, DirectoryIdentifier.IFD_BASELINE_DIRECTORY),
    IFD_TILE_BYTE_COUNTS(0x0145, DirectoryIdentifier.IFD_BASELINE_DIRECTORY),
    IFD_BAD_FAX_LINES(0x0146, DirectoryIdentifier.IFD_BASELINE_DIRECTORY),
    IFD_CLEAN_FAX_DATA(0x0147, DirectoryIdentifier.IFD_BASELINE_DIRECTORY),
    IFD_CONSECUTIVE_BAD_FAX_LINES(0x0148, DirectoryIdentifier.IFD_BASELINE_DIRECTORY),
    IFD_IFDSUB_POINTER(0x014A, DirectoryIdentifier.IFD_BASELINE_DIRECTORY),
    IFD_INK_SET(0x014C, DirectoryIdentifier.IFD_BASELINE_DIRECTORY),
    IFD_INK_NAMES(0x014D, DirectoryIdentifier.IFD_BASELINE_DIRECTORY),
    IFD_NUMBER_OF_INKS(0x014E, DirectoryIdentifier.IFD_BASELINE_DIRECTORY),
    IFD_DOT_RANGE(0x0150, DirectoryIdentifier.IFD_BASELINE_DIRECTORY),
    IFD_TARGET_PRINTER(0x0151, DirectoryIdentifier.IFD_BASELINE_DIRECTORY),
    IFD_EXTRA_SAMPLES(0x0152, DirectoryIdentifier.IFD_BASELINE_DIRECTORY),
    IFD_SAMPLE_FORMAT(0x0153, DirectoryIdentifier.IFD_BASELINE_DIRECTORY),
    IFD_SMIN_SAMPLE_VALUE(0x0154, DirectoryIdentifier.IFD_BASELINE_DIRECTORY),
    IFD_SMAX_SAMPLE_VALUE(0x0155, DirectoryIdentifier.IFD_BASELINE_DIRECTORY),
    IFD_TRANSFER_RANGE(0x0156, DirectoryIdentifier.IFD_BASELINE_DIRECTORY),
    IFD_CLIP_PATH(0x0157, DirectoryIdentifier.IFD_BASELINE_DIRECTORY),
    IFD_XCLIP_PATH_UNITS(0x0158, DirectoryIdentifier.IFD_BASELINE_DIRECTORY),
    IFD_YCLIP_PATH_UNITS(0x0159, DirectoryIdentifier.IFD_BASELINE_DIRECTORY),
    IFD_INDEXED(0x015A, DirectoryIdentifier.IFD_BASELINE_DIRECTORY),
    IFD_JPEG_TABLES(0x015B, DirectoryIdentifier.IFD_BASELINE_DIRECTORY),
    IFD_OPIPROXY(0x015F, DirectoryIdentifier.IFD_BASELINE_DIRECTORY),
    IFD_GLOBAL_PARAMETERS_IFD(0x0190, DirectoryIdentifier.IFD_BASELINE_DIRECTORY),
    IFD_PROFILE_TYPE(0x0191, DirectoryIdentifier.IFD_BASELINE_DIRECTORY),
    IFD_FAX_PROFILE(0x0192, DirectoryIdentifier.IFD_BASELINE_DIRECTORY),
    IFD_CODING_METHODS(0x0193, DirectoryIdentifier.IFD_BASELINE_DIRECTORY),
    IFD_VERSION_YEAR(0x0194, DirectoryIdentifier.IFD_BASELINE_DIRECTORY),
    IFD_MODE_NUMBER(0x0195, DirectoryIdentifier.IFD_BASELINE_DIRECTORY),
    IFD_DECODE(0x01B1, DirectoryIdentifier.IFD_BASELINE_DIRECTORY),
    IFD_DEFAULT_IMAGE_COLOR(0x01B2, DirectoryIdentifier.IFD_BASELINE_DIRECTORY),
    IFD_JPEG_PROC(0x0200, DirectoryIdentifier.IFD_BASELINE_DIRECTORY),
    IFD_JPEG_INTERCHANGE_FORMAT(0x0201, DirectoryIdentifier.IFD_BASELINE_DIRECTORY),
    IFD_JPEG_INTERCHANGE_FORMAT_LENGTH(0x0202, DirectoryIdentifier.IFD_BASELINE_DIRECTORY),
    IFD_JPEG_RESTART_INTERVAL(0x0203, DirectoryIdentifier.IFD_BASELINE_DIRECTORY),
    IFD_JPEG_LOSSLESS_PREDICTORS(0x0205, DirectoryIdentifier.IFD_BASELINE_DIRECTORY),
    IFD_JPEG_POINT_TRANSFORMS(0x0206, DirectoryIdentifier.IFD_BASELINE_DIRECTORY),
    IFD_JPEG_QTABLES(0x0207, DirectoryIdentifier.IFD_BASELINE_DIRECTORY),
    IFD_JPEG_DCTABLES(0x0208, DirectoryIdentifier.IFD_BASELINE_DIRECTORY),
    IFD_JPEG_ACTABLES(0x0209, DirectoryIdentifier.IFD_BASELINE_DIRECTORY),
    IFD_YCB_CR_COEFFICIENTS(0x0211, DirectoryIdentifier.IFD_BASELINE_DIRECTORY),
    IFD_YCB_CR_SUB_SAMPLING(0x0212, DirectoryIdentifier.IFD_BASELINE_DIRECTORY),
    IFD_YCB_CR_POSITIONING(0x0213, DirectoryIdentifier.IFD_BASELINE_DIRECTORY),
    IFD_REFERENCE_BLACK_WHITE(0x0214, DirectoryIdentifier.IFD_BASELINE_DIRECTORY),
    IFD_STRIP_ROW_COUNTS(0x022F, DirectoryIdentifier.IFD_BASELINE_DIRECTORY),
    IFD_XMP_DATA(0x02BC, DirectoryIdentifier.IFD_BASELINE_DIRECTORY),
    IFD_IMAGE_ID(0x800D, DirectoryIdentifier.IFD_BASELINE_DIRECTORY),
    IFD_COPYRIGHT(0x8298, DirectoryIdentifier.IFD_BASELINE_DIRECTORY),
    IFD_EXIF_POINTER(0x8769, DirectoryIdentifier.IFD_EXIF_SUBIFD_DIRECTORY),
    IFD_IMAGE_LAYER(0x87AC, DirectoryIdentifier.IFD_BASELINE_DIRECTORY),
    IFD_GPS_INFO_POINTER(0x8825, DirectoryIdentifier.IFD_GPS_DIRECTORY);

    private final int numID;
    private final DirectoryIdentifier directory;
    private final TagHint hint;

    private TagIFD_Baseline(int id, DirectoryIdentifier dir)
    {
        this(id, dir, TagHint.HINT_DEFAULT);
    }

    private TagIFD_Baseline(int id, DirectoryIdentifier dir, TagHint clue)
    {
        this.numID = id;
        this.directory = dir;
        this.hint = clue;
    }

    @Override
    public int getNumberID()
    {
        return numID;
    }

    @Override
    public DirectoryIdentifier getDirectoryType()
    {
        return directory;
    }

    @Override
    public TagHint getHint()
    {
        return hint;
    }
}