package tif.tagspecs;

import tif.DirectoryIdentifier;
import tif.TagHint;

public enum TagIFD_Private implements Taggable
{
    IFD_PROCESSING_SOFTWARE(0x000B, DirectoryIdentifier.IFD_ROOT_DIRECTORY),
    IFD_OLD_SUBFILE_TYPE(0x00FF, DirectoryIdentifier.IFD_ROOT_DIRECTORY),
    IFD_IMAGE_HEIGHT(0x0101, DirectoryIdentifier.IFD_ROOT_DIRECTORY),
    IFD_THRESHOLDING(0x0107, DirectoryIdentifier.IFD_ROOT_DIRECTORY),
    IFD_THUMBNAIL_OFFSET(0x0201, DirectoryIdentifier.IFD_ROOT_DIRECTORY),
    IFD_THUMBNAIL_LENGTH(0x0202, DirectoryIdentifier.IFD_ROOT_DIRECTORY),
    IFD_RATING(0x4746, DirectoryIdentifier.IFD_ROOT_DIRECTORY),
    IFD_RATING_PERCENT(0x4749, DirectoryIdentifier.IFD_ROOT_DIRECTORY),
    IFD_PIXEL_SCALE(0x830E, DirectoryIdentifier.IFD_ROOT_DIRECTORY),
    IFD_INTERGRAPH_MATRIX(0x8480, DirectoryIdentifier.IFD_ROOT_DIRECTORY),
    IFD_MODEL_TIE_POINT(0x8482, DirectoryIdentifier.IFD_ROOT_DIRECTORY),
    IFD_SEMINFO(0x8546, DirectoryIdentifier.IFD_ROOT_DIRECTORY),
    IFD_MODEL_TRANSFORM(0x85D8, DirectoryIdentifier.IFD_ROOT_DIRECTORY),
    IFD_PHOTOSHOP_SETTINGS(0x8649, DirectoryIdentifier.IFD_ROOT_DIRECTORY),
    IFD_ICC_PROFILE(0x8773, DirectoryIdentifier.IFD_ROOT_DIRECTORY, TagHint.HINT_MASK),
    IFD_GEO_TIFF_DIRECTORY(0x87AF, DirectoryIdentifier.IFD_ROOT_DIRECTORY),
    IFD_GEO_TIFF_DOUBLE_PARAMS(0x87B0, DirectoryIdentifier.IFD_ROOT_DIRECTORY),
    IFD_GEO_TIFF_ASCII_PARAMS(0x87B1, DirectoryIdentifier.IFD_ROOT_DIRECTORY),
    IFD_IMAGE_SOURCE_DATA(0x935C, DirectoryIdentifier.IFD_ROOT_DIRECTORY),
    IFD_XPTITLE(0x9C9B, DirectoryIdentifier.IFD_ROOT_DIRECTORY, TagHint.HINT_UCS2),
    IFD_XPCOMMENT(0x9C9C, DirectoryIdentifier.IFD_ROOT_DIRECTORY, TagHint.HINT_UCS2),
    IFD_XPAUTHOR(0x9C9D, DirectoryIdentifier.IFD_ROOT_DIRECTORY, TagHint.HINT_UCS2),
    IFD_XPKEYWORDS(0x9C9E, DirectoryIdentifier.IFD_ROOT_DIRECTORY, TagHint.HINT_UCS2),
    IFD_XPSUBJECT(0x9C9F, DirectoryIdentifier.IFD_ROOT_DIRECTORY, TagHint.HINT_UCS2),
    IFD_GDAL_METADATA(0xA480, DirectoryIdentifier.IFD_ROOT_DIRECTORY),
    IFD_GDAL_NO_DATA(0xA481, DirectoryIdentifier.IFD_ROOT_DIRECTORY),
    IFD_PRINT_IM(0xC4A5, DirectoryIdentifier.IFD_ROOT_DIRECTORY),
    IFD_DNG_VERSION(0xC612, DirectoryIdentifier.IFD_ROOT_DIRECTORY),
    IFD_DNG_BACKWARD_VERSION(0xC613, DirectoryIdentifier.IFD_ROOT_DIRECTORY),
    IFD_UNIQUE_CAMERA_MODEL(0xC614, DirectoryIdentifier.IFD_ROOT_DIRECTORY),
    IFD_LOCALIZED_CAMERA_MODEL(0xC615, DirectoryIdentifier.IFD_ROOT_DIRECTORY),
    IFD_COLOR_MATRIX1(0xC621, DirectoryIdentifier.IFD_ROOT_DIRECTORY),
    IFD_COLOR_MATRIX2(0xC622, DirectoryIdentifier.IFD_ROOT_DIRECTORY),
    IFD_CAMERA_CALIBRATION1(0xC623, DirectoryIdentifier.IFD_ROOT_DIRECTORY),
    IFD_CAMERA_CALIBRATION2(0xC624, DirectoryIdentifier.IFD_ROOT_DIRECTORY),
    IFD_REDUCTION_MATRIX1(0xC625, DirectoryIdentifier.IFD_ROOT_DIRECTORY),
    IFD_REDUCTION_MATRIX2(0xC626, DirectoryIdentifier.IFD_ROOT_DIRECTORY),
    IFD_ANALOG_BALANCE(0xC627, DirectoryIdentifier.IFD_ROOT_DIRECTORY),
    IFD_AS_SHOT_NEUTRAL(0xC628, DirectoryIdentifier.IFD_ROOT_DIRECTORY),
    IFD_AS_SHOT_WHITE_XY(0xC629, DirectoryIdentifier.IFD_ROOT_DIRECTORY),
    IFD_BASELINE_EXPOSURE(0xC62A, DirectoryIdentifier.IFD_ROOT_DIRECTORY),
    IFD_BASELINE_NOISE(0xC62B, DirectoryIdentifier.IFD_ROOT_DIRECTORY),
    IFD_BASELINE_SHARPNESS(0xC62C, DirectoryIdentifier.IFD_ROOT_DIRECTORY),
    IFD_LINEAR_RESPONSE_LIMIT(0xC62E, DirectoryIdentifier.IFD_ROOT_DIRECTORY),
    IFD_CAMERA_SERIAL_NUMBER(0xC62F, DirectoryIdentifier.IFD_ROOT_DIRECTORY),
    IFD_DNG_LENS_INFO(0xC630, DirectoryIdentifier.IFD_ROOT_DIRECTORY),
    IFD_SHADOW_SCALE(0xC633, DirectoryIdentifier.IFD_ROOT_DIRECTORY),
    IFD_SR2_PRIVATE(0xC634, DirectoryIdentifier.IFD_ROOT_DIRECTORY),
    IFD_MAKER_NOTE_SAFETY(0xC635, DirectoryIdentifier.IFD_ROOT_DIRECTORY),
    IFD_CALIBRATION_ILLUMINANT1(0xC65A, DirectoryIdentifier.IFD_ROOT_DIRECTORY),
    IFD_CALIBRATION_ILLUMINANT2(0xC65B, DirectoryIdentifier.IFD_ROOT_DIRECTORY),
    IFD_RAW_DATA_UNIQUE_ID(0xC65D, DirectoryIdentifier.IFD_ROOT_DIRECTORY),
    IFD_ORIGINAL_RAW_FILE_NAME(0xC68B, DirectoryIdentifier.IFD_ROOT_DIRECTORY),
    IFD_ORIGINAL_RAW_FILE_DATA(0xC68C, DirectoryIdentifier.IFD_ROOT_DIRECTORY),
    IFD_AS_SHOT_ICCPROFILE(0xC68F, DirectoryIdentifier.IFD_ROOT_DIRECTORY),
    IFD_AS_SHOT_PRE_PROFILE_MATRIX(0xC690, DirectoryIdentifier.IFD_ROOT_DIRECTORY),
    IFD_CURRENT_ICCPROFILE(0xC691, DirectoryIdentifier.IFD_ROOT_DIRECTORY),
    IFD_CURRENT_PRE_PROFILE_MATRIX(0xC692, DirectoryIdentifier.IFD_ROOT_DIRECTORY),
    IFD_COLORIMETRIC_REFERENCE(0xC6BF, DirectoryIdentifier.IFD_ROOT_DIRECTORY),
    IFD_SRAW_TYPE(0xC6C5, DirectoryIdentifier.IFD_ROOT_DIRECTORY),
    IFD_PANASONIC_TITLE(0xC6D2, DirectoryIdentifier.IFD_ROOT_DIRECTORY),
    IFD_PANASONIC_TITLE2(0xC6D3, DirectoryIdentifier.IFD_ROOT_DIRECTORY),
    IFD_CAMERA_CALIBRATION_SIG(0xC6F3, DirectoryIdentifier.IFD_ROOT_DIRECTORY),
    IFD_PROFILE_CALIBRATION_SIG(0xC6F4, DirectoryIdentifier.IFD_ROOT_DIRECTORY),
    IFD_PROFILE_IFD(0xC6F5, DirectoryIdentifier.IFD_ROOT_DIRECTORY),
    IFD_AS_SHOT_PROFILE_NAME(0xC6F6, DirectoryIdentifier.IFD_ROOT_DIRECTORY),
    IFD_PROFILE_NAME(0xC6F8, DirectoryIdentifier.IFD_ROOT_DIRECTORY),
    IFD_PROFILE_HUE_SAT_MAP_DIMS(0xC6F9, DirectoryIdentifier.IFD_ROOT_DIRECTORY),
    IFD_PROFILE_HUE_SAT_MAP_DATA1(0xC6FA, DirectoryIdentifier.IFD_ROOT_DIRECTORY),
    IFD_PROFILE_HUE_SAT_MAP_DATA2(0xC6FB, DirectoryIdentifier.IFD_ROOT_DIRECTORY),
    IFD_PROFILE_TONE_CURVE(0xC6FC, DirectoryIdentifier.IFD_ROOT_DIRECTORY),
    IFD_PROFILE_EMBED_POLICY(0xC6FD, DirectoryIdentifier.IFD_ROOT_DIRECTORY),
    IFD_PROFILE_COPYRIGHT(0xC6FE, DirectoryIdentifier.IFD_ROOT_DIRECTORY),
    IFD_FORWARD_MATRIX1(0xC714, DirectoryIdentifier.IFD_ROOT_DIRECTORY),
    IFD_FORWARD_MATRIX2(0xC715, DirectoryIdentifier.IFD_ROOT_DIRECTORY),
    IFD_PREVIEW_APPLICATION_NAME(0xC716, DirectoryIdentifier.IFD_ROOT_DIRECTORY),
    IFD_PREVIEW_APPLICATION_VERSION(0xC717, DirectoryIdentifier.IFD_ROOT_DIRECTORY),
    IFD_PREVIEW_SETTINGS_NAME(0xC718, DirectoryIdentifier.IFD_ROOT_DIRECTORY),
    IFD_PREVIEW_SETTINGS_DIGEST(0xC719, DirectoryIdentifier.IFD_ROOT_DIRECTORY),
    IFD_PREVIEW_COLOR_SPACE(0xC71A, DirectoryIdentifier.IFD_ROOT_DIRECTORY),
    IFD_PREVIEW_DATE_TIME(0xC71B, DirectoryIdentifier.IFD_ROOT_DIRECTORY),
    IFD_RAW_IMAGE_DIGEST(0xC71C, DirectoryIdentifier.IFD_ROOT_DIRECTORY),
    IFD_ORIGINAL_RAW_FILE_DIGEST(0xC71D, DirectoryIdentifier.IFD_ROOT_DIRECTORY),
    IFD_PROFILE_LOOK_TABLE_DIMS(0xC725, DirectoryIdentifier.IFD_ROOT_DIRECTORY),
    IFD_PROFILE_LOOK_TABLE_DATA(0xC726, DirectoryIdentifier.IFD_ROOT_DIRECTORY),
    IFD_TIME_CODES(0xC763, DirectoryIdentifier.IFD_ROOT_DIRECTORY),
    IFD_FRAME_RATE(0xC764, DirectoryIdentifier.IFD_ROOT_DIRECTORY),
    IFD_TSTOP(0xC772, DirectoryIdentifier.IFD_ROOT_DIRECTORY),
    IFD_REEL_NAME(0xC789, DirectoryIdentifier.IFD_ROOT_DIRECTORY),
    IFD_ORIGINAL_DEFAULT_FINAL_SIZE(0xC791, DirectoryIdentifier.IFD_ROOT_DIRECTORY),
    IFD_ORIGINAL_BEST_QUALITY_SIZE(0xC792, DirectoryIdentifier.IFD_ROOT_DIRECTORY),
    IFD_ORIGINAL_DEFAULT_CROP_SIZE(0xC793, DirectoryIdentifier.IFD_ROOT_DIRECTORY),
    IFD_CAMERA_LABEL(0xC7A1, DirectoryIdentifier.IFD_ROOT_DIRECTORY),
    IFD_PROFILE_HUE_SAT_MAP_ENCODING(0xC7A3, DirectoryIdentifier.IFD_ROOT_DIRECTORY),
    IFD_PROFILE_LOOK_TABLE_ENCODING(0xC7A4, DirectoryIdentifier.IFD_ROOT_DIRECTORY),
    IFD_BASELINE_EXPOSURE_OFFSET(0xC7A5, DirectoryIdentifier.IFD_ROOT_DIRECTORY),
    IFD_DEFAULT_BLACK_RENDER(0xC7A6, DirectoryIdentifier.IFD_ROOT_DIRECTORY),
    IFD_NEW_RAW_IMAGE_DIGEST(0xC7A7, DirectoryIdentifier.IFD_ROOT_DIRECTORY),
    IFD_RAW_TO_PREVIEW_GAIN(0xC7A8, DirectoryIdentifier.IFD_ROOT_DIRECTORY),
    IFD_DEPTH_FORMAT(0xC7E9, DirectoryIdentifier.IFD_ROOT_DIRECTORY),
    IFD_DEPTH_NEAR(0xC7EA, DirectoryIdentifier.IFD_ROOT_DIRECTORY),
    IFD_DEPTH_FAR(0xC7EB, DirectoryIdentifier.IFD_ROOT_DIRECTORY),
    IFD_DEPTH_UNITS(0xC7EC, DirectoryIdentifier.IFD_ROOT_DIRECTORY),
    IFD_DEPTH_MEASURE_TYPE(0xC7ED, DirectoryIdentifier.IFD_ROOT_DIRECTORY),
    IFD_ENHANCE_PARAMS(0xC7EE, DirectoryIdentifier.IFD_ROOT_DIRECTORY),
    IFD_CALIBRATION_ILLUMINANT3(0xCD31, DirectoryIdentifier.IFD_ROOT_DIRECTORY),
    IFD_CAMERA_CALIBRATION3(0xCD32, DirectoryIdentifier.IFD_ROOT_DIRECTORY),
    IFD_COLOR_MATRIX3(0xCD33, DirectoryIdentifier.IFD_ROOT_DIRECTORY),
    IFD_FORWARD_MATRIX3(0xCD34, DirectoryIdentifier.IFD_ROOT_DIRECTORY),
    IFD_ILLUMINANT_DATA1(0xCD35, DirectoryIdentifier.IFD_ROOT_DIRECTORY),
    IFD_ILLUMINANT_DATA2(0xCD36, DirectoryIdentifier.IFD_ROOT_DIRECTORY),
    IFD_ILLUMINANT_DATA3(0xCD37, DirectoryIdentifier.IFD_ROOT_DIRECTORY),
    IFD_PROFILE_HUE_SAT_MAP_DATA3(0xCD39, DirectoryIdentifier.IFD_ROOT_DIRECTORY),
    IFD_REDUCTION_MATRIX3(0xCD3A, DirectoryIdentifier.IFD_ROOT_DIRECTORY),
    IFD_RGB_TABLES(0xCD3F, DirectoryIdentifier.IFD_ROOT_DIRECTORY),
    IFD_PROFILE_GAIN_TABLE_MAP2(0xCD40, DirectoryIdentifier.IFD_ROOT_DIRECTORY),
    IFD_IMAGE_SEQUENCE_INFO(0xCD44, DirectoryIdentifier.IFD_ROOT_DIRECTORY),
    IFD_IMAGE_STATS(0xCD46, DirectoryIdentifier.IFD_ROOT_DIRECTORY),
    IFD_PROFILE_DYNAMIC_RANGE(0xCD47, DirectoryIdentifier.IFD_ROOT_DIRECTORY),
    IFD_PROFILE_GROUP_NAME(0xCD48, DirectoryIdentifier.IFD_ROOT_DIRECTORY),
    IFD_JXL_DISTANCE(0xCD49, DirectoryIdentifier.IFD_ROOT_DIRECTORY),
    IFD_JXL_EFFORT(0xCD4A, DirectoryIdentifier.IFD_ROOT_DIRECTORY),
    IFD_JXL_DECODE_SPEED(0xCD4B, DirectoryIdentifier.IFD_ROOT_DIRECTORY),
    IFD_SEAL(0xCEA1, DirectoryIdentifier.IFD_ROOT_DIRECTORY);

    private final int numID;
    private final DirectoryIdentifier directory;
    private final TagHint hint;

    private TagIFD_Private(int id, DirectoryIdentifier dir)
    {
        this(id, dir, TagHint.HINT_DEFAULT);
    }

    private TagIFD_Private(int id, DirectoryIdentifier dir, TagHint clue)
    {
        this.numID = id;
        this.directory = dir;
        this.hint = clue;
    }

    @Override
    public int getNumberID()
    {
        return numID;
    }

    @Override
    public DirectoryIdentifier getDirectoryType()
    {
        return directory;
    }

    @Override
    public TagHint getHint()
    {
        return hint;
    }
}